openmpf/openmpf

trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/OutputChecker.java

@jrobble Would you prefer this change, or should I just disable the test?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/56)

Change TestSystemOnDiff.runMotionSubsenseTrackingVideo to allow values near 30 in addition to 100.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java
trunk/workflow-manager/src/main/resources/tika-external-parsers.xml

Issue #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/64)

Add ability to detect video orientation from the video file's metadata.  Issue #57

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java
trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvDetectImageWithAutoOrientation.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/65)

Update auto-orientation test with new pipeline name

---

trunk/node-manager/src/main/java/org/mitre/mpf/nms/BaseServiceLauncher.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/68)

Fix BaseServiceLauncher variable interpolation issue.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestAddComponentService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestDescriptorFactory.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/74)

Fix bug causing NullPointerException when adding default action for descriptor that uses the propertiesKey field.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessorInterface.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionSplitterImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestArtifactExtractionProcessorAndSplitter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/76)

Fixed the way that extraction errors are reported.

---

pom.xml
trunk/mpf-system-tests/pom.xml
trunk/workflow-manager/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/141)

Add exclusions to mockito and junit so that hamcrest isn't imported multiple times

---

trunk/workflow-manager/pom.xml

Fixes an issue discovered while helping Erik get his dev environment set up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/143)

Add jsr-275 as separate dependency because the version referenced by tika no longer exists

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/WfmProcessingException.java

Issue #147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/148)

Make WfmProcessingException an unchecked exception

---

trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/OutputChecker.java
trunk/workflow-manager/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/150)

Confidence delta

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineServiceImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/160)

Fix task save bug

---

trunk/detection/test-components/java/JavaTestDetection/pom.xml
trunk/interop/pom.xml
trunk/workflow-manager/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/203)

Fix test component build order

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonJobRequest.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/205)

Fixed bug where job resubmission did not retain property settings.

---

trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvDetectVideoWithRegionOfInterest.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/208)

Add track to output runFaceOcvDetectVideoWithRegionOfInterest.json that was previously being dropped

---

trunk/ansible/install/ansible/roles/common/tasks/java.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/228)

Updated java.yml to use JDK and JRE 1.8.0_144.

---

trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/TestSystem.java
trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java
trunk/mpf-system-tests/src/test/resources/samples/text/NOTICE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/253)

Add OALPR w/ feed forward system tests

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/265)

Add key frame test

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java
trunk/mpf-system-tests/src/test/resources/samples/object/NOTICE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/278)

Add system tests for Caffe feed forward

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/MediaSegmenter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/282)

Add REGION to acceptable feed forward types

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/298)

Fixed testBadPipeline() by expecting exception.

---

trunk/detection/executor/cpp/MPFDetectionBuffer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/324)

Now properly setting value when copying feed forward location detection properties.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/jobcreation/JobCreationProcessor.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/css/app.css
trunk/workflow-manager/src/main/webapp/resources/mytheme/css/styles.css
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js

Improved job status progress bar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/340)

Improved job status notifications through atmosphere.

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/357)

Fix bad pipeline test

---

trunk/mpf-install/node-manager-only-pom.xml
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/TransientJob.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JsonUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/373)

Updated node-manager-only-pom.xml.

---

trunk/mpf-install/node-manager-only-pom.xml
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/TransientJob.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JsonUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/379)

Fix conflicts to merge master into develop

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/StreamingJobRequestBo.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/StreamingJobRoutesBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/375)

Add Camel routes for streaming jobs.

---

trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/JobCreationResponse.java
trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/MpfResponse.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/NodeController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/StreamingJobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/SystemMessageController.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITComponentLifecycle.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java

Issue #343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/378)

Use constants for MpfResponse.responseCode.

---

trunk/mpf-install/src/main/scripts/mpf-profile.sh
trunk/protobuf/CMakeLists.txt

Removed LD_LIBRARY_PATH export from mpf-profile.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/393)

Now compiling libmpfProtobufs as STATIC.

---

trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp
trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/396)

StreamingHelloWorld revised api

---

trunk/detection/test-components/cpp/CplusplusHelloWorld/HelloWorld.cpp

Issue #398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/399)

Fix CplusplusHelloWorld component logging

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/StreamingJobController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/406)

added isActive parameter to [GET] /rest/streaming/jobs

---

trunk/detection/executor/cpp/streaming/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/422)

Fixed frame number checks in C++ streaming component executor.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/MpfServiceImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/431)

Updated submitJob() methods to throw exceptions.

---

trunk/bin/mpf-scripts/mpf/mpf_clean.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/432)

"mpf clean" now cleans out streaming_job_request table.

---

trunk/detection/executor/cpp/streaming/BasicAmqMessageSender.cpp
trunk/detection/executor/cpp/streaming/BasicAmqMessageSender.h
trunk/detection/executor/cpp/streaming/CMakeLists.txt
trunk/detection/executor/cpp/streaming/ExecutorUtils.cpp
trunk/detection/executor/cpp/streaming/ExecutorUtils.h
trunk/detection/executor/cpp/streaming/main.cpp
trunk/detection/executor/cpp/streaming/test/CMakeLists.txt
trunk/detection/executor/cpp/streaming/test/test_streaming_executor.cpp
trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp
trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.h
trunk/protobuf/src/main/proto/detection.proto
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/StreamingJobRoutesBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/SegmentSummaryReport.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/429)

Add timestamps to summary report

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/444)

Update streaming job status in REDIS before mySQL.

---

pom.xml
trunk/ansible/install-mpf.sh
trunk/ansible/install/ansible/mpf-master.yml
trunk/detection/executor/java/pom.xml
trunk/detection/test-components/cpp/CplusplusHelloWorld/plugin-files/descriptor/descriptor.json
trunk/detection/test-components/java/JavaTestDetection/plugin-files/descriptor/JavaTestDetection.json
trunk/detection/test-components/java/JavaTestDetection/pom.xml
trunk/detection/test-components/java/pom.xml
trunk/interop/pom.xml
trunk/jenkins/scripts/CreateCustomPackage.pl
trunk/markup/pom.xml
trunk/mpf-install/base-pom.xml
trunk/mpf-install/node-manager-only-pom.xml
trunk/mpf-install/pom.xml
trunk/mpf-rest-api/pom.xml
trunk/mpf-rest-client/pom.xml
trunk/mpf-system-tests/pom.xml
trunk/mpf-system-tests/src/test/resources/jenkins/nodeServicesPalette.json
trunk/node-manager/pom.xml
trunk/node-manager/src/scripts/start-java-component.sh
trunk/node-manager/src/scripts/start-nodemanager.sh
trunk/pom.xml
trunk/protobuf/pom.xml
trunk/video-overlay/pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/resources/templates/nodeServicesPalette.json
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestJsonDescriptor.java
trunk/workflow-manager/src/test/resources/CplusplusHelloCustomPipelinesComponent.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/448)

Updated version numbers to 2.0.0.

---

trunk/detection/executor/cpp/streaming/StreamingComponentExecutor.cpp
trunk/detection/executor/cpp/streaming/StreamingComponentExecutor.h
trunk/detection/executor/cpp/streaming/StreamingVideoCapture.cpp
trunk/detection/executor/cpp/streaming/StreamingVideoCapture.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/450)

Make streaming component executor use frame transformers.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/458)

Include job ids in log message when sending callbacks.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/462)

Set log level for "About to send" callback lines to debug.

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonSegmentSummaryReport.java
trunk/interop/src/main/java/org/mitre/mpf/interop/JsonStreamingDetectionOutputObject.java
trunk/interop/src/main/java/org/mitre/mpf/interop/JsonStreamingTrackOutputObject.java
trunk/interop/src/main/java/org/mitre/mpf/interop/util/CompareUtils.java
trunk/interop/src/main/java/org/mitre/mpf/interop/util/TimeUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/StreamingJobRoutesBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/465)

Use human readable timestamps for streaming output objects.

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonHealthReportCollection.java
trunk/interop/src/main/java/org/mitre/mpf/interop/JsonSegmentSummaryReport.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/473)

add @JsonPropertyDescription to fields in JsonHealthReportCollection

---

trunk/detection/executor/cpp/streaming/ExecutorUtils.cpp
trunk/detection/executor/cpp/streaming/ExecutorUtils.h
trunk/detection/executor/cpp/streaming/StreamingComponentExecutor.cpp
trunk/detection/executor/cpp/streaming/StreamingComponentExecutor.h
trunk/detection/executor/cpp/streaming/test/test_streaming_executor.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/466)

Fix end segment issue

---

trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp
trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/474)

Make CplusplusHelloWorldComponent use confidence threshold.

---

trunk/mpf-install/src/main/assembly/mpf-install-dep-assembly.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/478)

Add streaming_component_executor to deployment package

---

trunk/interop/src/test/java/org/mitre/mpf/SchemaCreator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/484)

Added health report and segment summary report classes to interop schema creator.

---

trunk/mpf-system-tests/pom.xml
trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JniLoader.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/486)

Fix java.library.path in system tests

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java
trunk/mpf-system-tests/src/test/resources/output/object/runDarknetDetectVideo.json
trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/514)

Add detection.models.dir.path property.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/xml/PropertyDefinition.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/516)

Make property interpolation work for algo properties that use propertiesKey

---

trunk/detection/executor/cpp/common/MPFMessageUtils.cpp
trunk/protobuf/src/main/proto/detection.proto
trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/536)

Add CUDA properties.

---

trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/539)

Add MPF_GPU_ERROR to Java component executor

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionSplitter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/547)

Fixed video segmenting on single-frame gifs.

---

trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml
trunk/ansible/install/ansible/roles/child/tasks/compregistration.yml
trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml
trunk/ansible/install/ansible/roles/common/tasks/main.yml
trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp
trunk/detection/executor/cpp/batch/PythonComponentHandle.h
trunk/detection/executor/cpp/batch/main.cpp
trunk/detection/executor/cpp/batch/test/CMakeLists.txt
trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp
trunk/detection/executor/cpp/batch/test/test_python_components/test_env_activate.py
trunk/mpf-install/base-pom.xml
trunk/mpf-install/src/main/assembly/mpf-install-dep-assembly.xml
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AnsibleDeploymentService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/565)

Add support for setuptools Python components and automatically create virtualenv during component registration.

---

trunk/detection/executor/cpp/batch/CMakeLists.txt
trunk/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/578)

Update pom to run Python unit tests

---

pom.xml
trunk/ansible/install-mpf.sh
trunk/ansible/install/ansible/mpf-master.yml
trunk/bin/mpf-scripts/setup.py
trunk/detection/executor/java/pom.xml
trunk/detection/test-components/cpp/CplusplusHelloWorld/plugin-files/descriptor/descriptor.json
trunk/detection/test-components/java/JavaTestDetection/plugin-files/descriptor/JavaTestDetection.json
trunk/detection/test-components/java/JavaTestDetection/pom.xml
trunk/detection/test-components/java/pom.xml
trunk/interop/pom.xml
trunk/jenkins/scripts/CreateCustomPackage.pl
trunk/markup/pom.xml
trunk/mpf-install/base-pom.xml
trunk/mpf-install/node-manager-only-pom.xml
trunk/mpf-install/pom.xml
trunk/mpf-rest-api/pom.xml
trunk/mpf-rest-client/pom.xml
trunk/mpf-system-tests/pom.xml
trunk/mpf-system-tests/src/test/resources/jenkins/nodeServicesPalette.json
trunk/node-manager/pom.xml
trunk/node-manager/src/scripts/start-java-component.sh
trunk/node-manager/src/scripts/start-nodemanager.sh
trunk/pom.xml
trunk/protobuf/pom.xml
trunk/video-overlay/pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/resources/templates/nodeServicesPalette.json
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestJsonDescriptor.java
trunk/workflow-manager/src/test/resources/CplusplusHelloCustomPipelinesComponent.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/598)

Updated version to 2.1.0.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/600)

Modify JobController so that it doesn't say a job does not exist just because it is not in user's session.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/595)

Fix artifact extraction resubmit issues

---

trunk/ansible/install/ansible/mpf-master.yml
trunk/ansible/install/ansible/roles/master/files/set-markup-ld-path.py
trunk/node-manager/src/main/java/org/mitre/mpf/nms/streaming/StreamingProcessFactory.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/admin/AdminNodesCtrl.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/606)

Nodes UI no longer disables buttons for a full lockout period when deleting a stopped service.

---

trunk/CMakeLists.txt
trunk/detection/executor/cpp/batch/CMakeLists.txt
trunk/detection/executor/cpp/batch/test/CMakeLists.txt
trunk/detection/executor/cpp/streaming/CMakeLists.txt
trunk/detection/executor/cpp/streaming/MessageUtils/test/CMakeLists.txt
trunk/protobuf/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/632)

Statically link to protobuf runtime library.

---

trunk/ansible/install/ansible/roles/child/templates/mpf-profile.sh.j2
trunk/ansible/install/ansible/roles/master/templates/mpf-profile.sh.j2
trunk/jenkins/scripts/MPF/Jenkins.pm
trunk/mpf-install/src/main/scripts/mpf-profile.sh
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/643)

Setting MYSQL_HOST and REDIS_HOST to localhost.

---

trunk/jenkins/scripts/config_files/openmpf-open-source-package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/650)

Added Darknet to openmpf-open-source-package.json.

---

trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json
trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvDetectVideo.json
trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvDetectVideoWithRegionOfInterest.json
trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsVideo.json
trunk/mpf-system-tests/src/test/resources/output/motion/runMogMotionPreprocessingFaceDetectionMarkup.json
trunk/mpf-system-tests/src/test/resources/output/speech/runSpeechSphinxDetectVideo.json
trunk/mpf-system-tests/src/test/resources/output/text/runTextOalprDetectVideo.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/646)

Update system test output with track confidence

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/666)

Add system test for darknet streaming.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobStatusCalculator.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediaretrieval/RemoteMediaProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfHeaders.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/services.js
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/684)

Fixed bugs related to reporting final job status.

---

trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java
trunk/mpf-system-tests/src/test/resources/output/object/runDarknetDetectVideo.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/683)

Update system tests for YoloV3.

---

trunk/ansible/install/ansible/roles/sys-common/tasks/main.yml
trunk/node-manager/src/scripts/log4bash.sh
trunk/node-manager/src/scripts/node-manager

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/705)

Fixed unary operator issue related to "su -".

---

trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java
trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java
trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFMessageMetadata.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/724)

Java component executor now properly uses job ID for the job name.

---

trunk/node-manager/src/main/java/org/mitre/mpf/nms/ChannelReceiver.java
trunk/node-manager/src/main/resources/jGroupsTCPConfig.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/726)

Fix node launch

---

pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/applicationContext-hibernate.xml
trunk/workflow-manager/src/main/webapp/resources/mytheme/json/dependencies.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/735)

Replace BoneCP with Apache commons BasicDataSource to avoid issues when temporarily disconnected from MySQL.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/741)

Merge track level properties when merging two tracks.

---

trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMain.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/757)

Now setting run directory in Java component executor.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/CustomPipelineValidatorImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/755)

Fixed bug where actions could not be added using an "extras" component.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/AdminPropertySettingsController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/AtmosphereController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/model/AtmosphereChannel.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/model/AtmosphereMessage.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledStringCountBasedWfmAggregator.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/EndOfStageProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/jobcreation/JobCreationProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobStatusBroadcaster.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/webapp/WEB-INF/html/jobs/layout.html
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/services.js
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/admin/AdminPropertySettingsCtrl.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/769)

Add property to disable job status broadcasts.

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/788)

Add @JsonPropertyDescription to JsonOutputObject's jobErrors and jobWarnings fields

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobStatusCalculator.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediaretrieval/RemoteMediaProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfHeaders.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/services.js
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js

* Now performs multiple remote media download attempts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/703)

Fixed bugs related to reporting final job status. (#684)

---

trunk/interop/README.md
trunk/interop/src/main/java/org/mitre/mpf/interop/util/InstantJsonModule.java
trunk/interop/src/main/java/org/mitre/mpf/interop/util/MpfObjectMapper.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JsonUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/823)

Move InstantJsonModule to interop package

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/StreamingJobController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/837)

Mentioned that all provided URIs must be properly encoded.

---

trunk/detection/executor/cpp/batch/main.cpp
trunk/jenkins/scripts/config_files/openmpf-open-source-package.json
trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/component/RegisterComponentModel.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/RestBasicAuthEntryPoint.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/AdminComponentRegistrationController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AnsibleDeploymentService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/DuplicateComponentException.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/JsonComponentDescriptor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/RemoveComponentServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/StartupComponentRegistrationServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/applicationContext-spring-security.xml
trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/admin/AdminComponentRegistrationCtrl.js
trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/controller/TestAdminComponentRegistrationController.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestAddComponentService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestRemoveComponentService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestStartupComponentRegistrationService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/878)

Unmanaged component registration

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/MediaSegmenter.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestMediaSegmenter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/890)

Fixed MIN_SEGMENT_LENGTH off-by-one error.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/RemoveComponentServiceImpl.java

(Issue #889)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/902)

Fix issue with unmanaged component registration after container restart. (Issue #889)

---

trunk/jenkins/scripts/config_files/openmpf-open-source-package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/892)

Added EAST component to openmpf-open-source-package.json.

---

trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvDetectImageWithAutoOrientation.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/923)

Update output object for TestSystemOnDiff.runFaceOcvDetectImageWithAutoOrientation

---

trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/JobPageModel.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/AbstractHibernateDao.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateDao.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDao.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/MpfService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/MpfServiceImpl.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js

https://github.com/openmpf/openmpf/issues/798
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/916)

Optimize jobs query

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/943)

Now dropping all duplicate messages in the DLQ.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/945)

Now using mutually exclusive selectors for DLQ consumers.

---

trunk/mpf-rest-client/README.md
trunk/mpf-rest-client/src/main/java/org/mitre/mpf/rest/client/Main.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1001)

Refactor example REST client.

---

pom.xml
trunk/bin/mpf-scripts/mpf/mpf_clean.py
trunk/bin/mpf-scripts/mpf/mpf_sys.py
trunk/bin/mpf-scripts/mpf/mpf_users.py
trunk/bin/mpf-scripts/mpf/mpf_util.py
trunk/bin/mpf-scripts/setup.py
trunk/jenkins/scripts/1-EnvironmentClean.pl
trunk/jenkins/scripts/2-EnvironmentRun.pl
trunk/jenkins/scripts/C-Teardown.pl
trunk/jenkins/scripts/MPF/Jenkins.pm
trunk/mpf-install/src/main/scripts/mpf-profile.sh
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/SystemMessageController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/EnhancedPostgreSQLDialect.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/ImprovedNamingStrategy.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/JobRequest.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MarkupResult.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/StreamingJobRequest.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/SystemMessage.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/User.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/UserRole.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/UserService.java
trunk/workflow-manager/src/main/resources/applicationContext-hibernate.xml
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/webapp/resources/mytheme/json/dependencies.json
trunk/workflow-manager/src/test/README.md
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestUserService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1013)

Merge postgres to develop

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java

Needs to be merged w/ fast forward
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1014)

Merge job router to master

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1018)

Merge job router to develop

---

trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1019)

Remove dependency on external rtsp stream from ITWebStreamingReports.

---

trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1020)

hf-merge/fix streaming reports tests

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1039)

Fix check for detection padding system properties.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1040)

Hotfix merge master/detection padding system properties

---

trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/TestSystem.java
trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Detection.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1041)

Update detection padding for R4.1.

---

pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/applicationContext-hibernate.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1049)

Update hibernate and its depencies versions

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonCallbackBody.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1055)

Add output object uri to callback

---

trunk/workflow-manager/src/main/resources/workflow-properties.json

I tested OcvFaceDetection with images rotated at 90 and 45 degrees by specifying ROTATION through Swagger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1059)

Update ROTATION description in workflow-properties.json.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

I backported the TestDlqRouteBuilder updates from develop and improved the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1061)

Generalize DLQ duplicate message check.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1074)

Hf merge master/dlq suppressing dup check

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1077)

Hf merge develop/dlq suppressing dup check

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/ThreadUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1072)

Add job warning when callback fails.

---

trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1087)

Update mpf.version.semantic property.

---

trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1090)

Hf merge develop/mpf version

---

trunk/jenkins/scripts/config_files/openmpf-open-source-package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1088)

Add AzureOcr to openmpf-open-source-package.json

---

trunk/jenkins/scripts/config_files/openmpf-open-source-package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1091)

hf-merge/acs-ocr

---

trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1102)

Fix python component handle test

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1110)

Update media inspection to support webp images.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1111)

Hotfix merge develop/support webp

---

trunk/CMakeLists.txt
trunk/detection/executor/cpp/batch/CMakeLists.txt
trunk/detection/executor/cpp/batch/MPFDetectionBuffer.cpp
trunk/detection/executor/cpp/batch/MPFDetectionBuffer.h
trunk/detection/executor/cpp/batch/MPFMessenger.cpp
trunk/detection/executor/cpp/batch/MPFMessenger.h
trunk/detection/executor/cpp/batch/main.cpp
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

Associated PRs:
- https://github.com/openmpf/openmpf/pull/1113
- https://github.com/openmpf/openmpf-docker/pull/96
Issues:
- https://github.com/openmpf/openmpf/issues/1104
- https://github.com/openmpf/openmpf/issues/585
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1113)

Fix C++ executor memory leaks and memory management in general.

---

trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java
trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvDetectImageWithAutoOrientation.json
trunk/protobuf/src/main/proto/markup.proto
trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp
trunk/video-overlay/src/main/cpp/FrameExtractor.cpp
trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/BoundingBox.java
trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/BoundingBoxMap.java
trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBox.java
trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBoxMap.java
trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBoxWriter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java

Issues: 
- https://github.com/openmpf/openmpf/issues/1108
- https://github.com/openmpf/openmpf/issues/1035
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1114
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/86
- https://github.com/openmpf/openmpf-python-component-sdk/pull/24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1114)

Fix bug when doing markup with flip.

---

trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1126)

Fix TestDlqRouteBuilder.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties

Issue: https://github.com/openmpf/openmpf/issues/1138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1139)

Retry HTTP callbacks and increase timeout.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1140)

Drop "duplicate paged in from cursor" DLQ messages.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/ThreadUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

Merge to master of https://github.com/openmpf/openmpf/pull/1139 and https://github.com/openmpf/openmpf/pull/1140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1142)

hf-merge-master/retry-callback

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/ThreadUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/TestDlqRouteBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1144)

hf-merge-develop/retry-callback

---

trunk/workflow-manager/src/main/resources/applicationContext-jms.xml

…to CLIENT_ACKNOWLEDGE instead of AUTO_ACKNOWLEDGE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1143)

Set Camel acknowledgement mode

---

trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1147)

Upgrade pip within virtual env before installing component.

---

trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml

Merges: https://github.com/openmpf/openmpf/pull/1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1149)

hf-merge-develop/upgrade-pip-in-venv

---

trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml
trunk/workflow-manager/src/main/resources/applicationContext-jms.xml

Merges https://github.com/openmpf/openmpf/pull/1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1150)

hf-merge/upgrade-pip-in-venv

---

trunk/interop/pom.xml
trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java
trunk/interop/src/main/java/org/mitre/mpf/interop/util/CompareUtils.java

Issue: https://github.com/openmpf/openmpf/issues/1153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1154)

Make interop package use Java 8.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/VideoMediaSegmenter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1164)

Pass feed-forward track properties along with feed-forward tracks.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/VideoMediaSegmenter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1166)

Hf merge/feed forward track properties

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1183)

Add missing synchronized to InProgressBatchJobsService

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1184)

hf-merge-master/missing-sync-inprogress-jobs

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1185)

hf-merge-develop/missing-sync-inprogress-jobs

---

trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json
trunk/mpf-system-tests/src/test/resources/output/motion/runMogMotionPreprocessing.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1201)

Fix nightly system tests

---

trunk/detection/executor/cpp/batch/BatchExecutorUtil.cpp
trunk/detection/executor/cpp/batch/BatchExecutorUtil.h
trunk/detection/executor/cpp/batch/CMakeLists.txt
trunk/detection/executor/cpp/batch/main.cpp
trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp
trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java
trunk/detection/executor/java/src/test/java/org/mitre/mpf/component/executor/detection/TestMPFDetectionMain.java

Resolves #1206 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1214)

Allow job properties to be set through environment variables.

---

trunk/detection/executor/cpp/batch/BatchExecutorUtil.cpp
trunk/detection/executor/cpp/batch/BatchExecutorUtil.h
trunk/detection/executor/cpp/batch/CMakeLists.txt
trunk/detection/executor/cpp/batch/main.cpp
trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp
trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java
trunk/detection/executor/java/src/test/java/org/mitre/mpf/component/executor/detection/TestMPFDetectionMain.java

Merges https://github.com/openmpf/openmpf/pull/1214 in to develop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1217)

Merges: Allow job properties to be set through environment variables. (#1214)

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/CensorPropertiesService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JsonUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestCensorPropertiesService.java

Issue: https://github.com/openmpf/openmpf/issues/1219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1222)

Add ability to censor property output

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestS3StorageBackend.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1225)

Prevent S3 storage service from using keys after they have been censored

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/CensorPropertiesService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JsonUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestCensorPropertiesService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestS3StorageBackend.java

Merges https://github.com/openmpf/openmpf/pull/1225 and https://github.com/openmpf/openmpf/pull/1222 into master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1228)

hf-merge-master/fix-s3-storage

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/CensorPropertiesService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JsonUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestCensorPropertiesService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestS3StorageBackend.java

Merges https://github.com/openmpf/openmpf/pull/1228 in to develop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1229)

Merge Add ability to censor property output to develop

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1239)

Fix NullPointerException when media cannot be downloaded.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1240)

Hf merge/fix media download npe

---

trunk/workflow-manager/src/main/resources/tika-external-parsers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1247)

Add -nostats to Tika's ffmpeg command

---

trunk/workflow-manager/src/main/resources/tika-external-parsers.xml

Merges https://github.com/openmpf/openmpf/pull/1247 in to develop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1248)

hf-merge/ffmpeg-no-stats-output

---

trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1274)

Increase sleep for testJobWithCallback.

---

trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebREST.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1275)

Hf merge/test job with callback

---

trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/resources/workflow-properties.json

Issue: https://github.com/openmpf/openmpf/issues/1270
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1276
- https://github.com/openmpf/openmpf-components/pull/237
- https://github.com/openmpf/openmpf-python-component-sdk/pull/41
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1276)

Add detection.http.retry.* properties.

---

logging-dependencies.xml
pom.xml
trunk/bin/mpf-scripts/setup.py
trunk/detection/executor/java/pom.xml
trunk/detection/test-components/cpp/CplusplusHelloWorld/plugin-files/descriptor/descriptor.json
trunk/detection/test-components/java/JavaTestDetection/plugin-files/descriptor/JavaTestDetection.json
trunk/detection/test-components/java/JavaTestDetection/pom.xml
trunk/detection/test-components/java/pom.xml
trunk/interop/pom.xml
trunk/markup/pom.xml
trunk/mpf-install/base-pom.xml
trunk/mpf-install/node-manager-only-pom.xml
trunk/mpf-install/pom.xml
trunk/mpf-rest-api/pom.xml
trunk/mpf-rest-client/pom.xml
trunk/mpf-system-tests/pom.xml
trunk/mpf-system-tests/src/test/resources/jenkins/nodeServicesPalette.json
trunk/node-manager/pom.xml
trunk/node-manager/src/scripts/start-java-component.sh
trunk/node-manager/src/scripts/start-nodemanager.sh
trunk/pom.xml
trunk/protobuf/pom.xml
trunk/video-overlay/pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/resources/templates/nodeServicesPalette.json
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestJsonDescriptor.java
trunk/workflow-manager/src/test/resources/CplusplusHelloCustomPipelinesComponent.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1286)

Update versions to 6.1.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionSplitterImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1288)

Don't skip artifact extraction for failed media.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionSplitterImpl.java

Merges: https://github.com/openmpf/openmpf/pull/1288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1289)

Don't skip artifact extraction for failed media. (#1288)

---

trunk/detection/executor/cpp/batch/MPFMessenger.cpp
trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java
trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java
trunk/markup/src/main/resources/activeMqConfig.xml
trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp
trunk/video-overlay/src/main/cpp/FrameExtractor.cpp
trunk/video-overlay/src/main/cpp/JniHelper.cpp
trunk/video-overlay/src/main/cpp/JniHelper.h
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/ResponseProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1293)

Fix priority and limit JNI memory usage

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1305)

Parallel artifact S3 uploads

---

trunk/protobuf/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1291)

Use Mapr repository for protoc plugin.

---

trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/JobPageModel.java
trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/SingleJobInfo.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITComponentLifecycle.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1250
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1320)

Include media uris in job status rest endpoint.

---

logging-dependencies.xml
pom.xml
trunk/bin/mpf-scripts/setup.py
trunk/detection/executor/java/pom.xml
trunk/detection/test-components/cpp/CplusplusHelloWorld/plugin-files/descriptor/descriptor.json
trunk/detection/test-components/java/JavaTestDetection/plugin-files/descriptor/JavaTestDetection.json
trunk/detection/test-components/java/JavaTestDetection/pom.xml
trunk/detection/test-components/java/pom.xml
trunk/interop/pom.xml
trunk/markup/pom.xml
trunk/mpf-install/base-pom.xml
trunk/mpf-install/node-manager-only-pom.xml
trunk/mpf-install/pom.xml
trunk/mpf-rest-api/pom.xml
trunk/mpf-rest-client/pom.xml
trunk/mpf-system-tests/pom.xml
trunk/mpf-system-tests/src/test/resources/jenkins/nodeServicesPalette.json
trunk/node-manager/pom.xml
trunk/node-manager/src/scripts/start-java-component.sh
trunk/node-manager/src/scripts/start-nodemanager.sh
trunk/pom.xml
trunk/protobuf/pom.xml
trunk/video-overlay/pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/resources/templates/nodeServicesPalette.json
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestJsonDescriptor.java
trunk/workflow-manager/src/test/resources/CplusplusHelloCustomPipelinesComponent.json

**Issues:**
- https://github.com/openmpf/openmpf/issues/1322
- https://github.com/openmpf/openmpf/pull/1321
- https://github.com/openmpf/openmpf-components/pull/253
- https://github.com/openmpf/openmpf-contrib-components/pull/72
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/106
- https://github.com/openmpf/openmpf-python-component-sdk/pull/49
- https://github.com/openmpf/openmpf-java-component-sdk/pull/53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1321)

Update versions to 6.2.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/CorsFilter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/RestBasicAuthEntryPoint.java
trunk/workflow-manager/src/main/webapp/WEB-INF/applicationContext-web.xml
trunk/workflow-manager/src/main/webapp/WEB-INF/web.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1367
Tested by running `python3 -m http.server` in the directory containing `index.html` with the following content:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
<body>
<p>test</p>
<button id="send-job-btn">Send Job</button>
<ul id="responses"></ul>
<script type="text/javascript">
document.querySelector('#send-job-btn').addEventListener('click', async () => {
let job_id = null;
try {
const post_resp = await axios.post('http://localhost:8080/workflow-manager/rest/jobs',
{
algorithmProperties: {},
buildOutput: true,
jobProperties: {},
media: [
{
mediaUri: 'file:///opt/mpf/share/remote-media/face.jpg',
properties: {} …
```

Enable CORS

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/CorsFilter.java
trunk/workflow-manager/src/main/webapp/WEB-INF/web.xml

Merges: https://github.com/openmpf/openmpf/pull/1368
**Issues:**
- https://github.com/openmpf/openmpf/issues/1367
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1369)

hf-merge/enable-cors

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MediaController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/css/app.css
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/ServerMediaCtrl.js

Merges: https://github.com/openmpf/openmpf/pull/1376
**Issues:**
- https://github.com/openmpf/openmpf/issues/1373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1385)

Hf merge/wfm file upload issue

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonMediaOutputObject.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1378)

Sort JsonMediaOutputObject by mediaId

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMarkupResponseProcessor.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1392)

Don't try to store markup that doesn't exist

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMarkupResponseProcessor.java

Merges: https://github.com/openmpf/openmpf/pull/1392
**Issues:**
- https://github.com/openmpf/openmpf/issues/1391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1393)

hf-merge/upload-failed-markup

---

logging-dependencies.xml
pom.xml
trunk/bin/mpf-scripts/setup.py
trunk/detection/executor/java/pom.xml
trunk/detection/test-components/cpp/CplusplusHelloWorld/plugin-files/descriptor/descriptor.json
trunk/detection/test-components/java/JavaTestDetection/plugin-files/descriptor/JavaTestDetection.json
trunk/detection/test-components/java/JavaTestDetection/pom.xml
trunk/detection/test-components/java/pom.xml
trunk/interop/pom.xml
trunk/markup/pom.xml
trunk/mpf-install/base-pom.xml
trunk/mpf-install/node-manager-only-pom.xml
trunk/mpf-install/pom.xml
trunk/mpf-rest-api/pom.xml
trunk/mpf-rest-client/pom.xml
trunk/mpf-system-tests/pom.xml
trunk/mpf-system-tests/src/test/resources/jenkins/nodeServicesPalette.json
trunk/node-manager/pom.xml
trunk/node-manager/src/scripts/start-java-component.sh
trunk/node-manager/src/scripts/start-nodemanager.sh
trunk/pom.xml
trunk/protobuf/pom.xml
trunk/video-overlay/pom.xml
trunk/workflow-manager/pom.xml
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/main/resources/templates/nodeServicesPalette.json
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/component/TestJsonDescriptor.java
trunk/workflow-manager/src/test/resources/CplusplusHelloCustomPipelinesComponent.json

**Issues:**
- https://github.com/openmpf/openmpf/issues/1401
- https://github.com/openmpf/openmpf/pull/1400
- https://github.com/openmpf/openmpf-components/pull/279
- https://github.com/openmpf/openmpf-contrib-components/pull/75
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/107
- https://github.com/openmpf/openmpf-python-component-sdk/pull/56
- https://github.com/openmpf/openmpf-java-component-sdk/pull/54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1400)

Update versions to 6.3.

---

trunk/workflow-manager/src/main/resources/properties/mpf.properties

**Issues:**
- https://github.com/openmpf/openmpf/issues/1406
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1409)

Hf merge/illformed detection type text

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/transformation/DetectionTransformationProcessor.java

Issue: https://github.com/openmpf/openmpf/issues/1411
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1410)

Fix duplicate SHRUNK_TO_NOTHING exception.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/transformation/DetectionTransformationProcessor.java

Merges: https://github.com/openmpf/openmpf/pull/1410
Issue: https://github.com/openmpf/openmpf/issues/1411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1412)

hf-merge/dup-shrunk-to-nothing

---

trunk/workflow-manager/src/main/resources/properties/mpf.properties

**Issues:**
- https://github.com/openmpf/openmpf/issues/1413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1419)

Hf merge/illformed detection type translation

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/AdminStatisticsController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java
trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/stats/layout.html
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/admin/AdminStatsCtrl.js

**Issues:**
- https://github.com/openmpf/openmpf/issues/1441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1446)

Use group by query for job stats.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/AdminStatisticsController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java
trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/stats/layout.html
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/admin/AdminStatsCtrl.js

Merges: https://github.com/openmpf/openmpf/pull/1446
**Issues:**
- https://github.com/openmpf/openmpf/issues/1441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1448)

Use group by query for job stats. (#1446)

---

trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/stats/layout.html
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/admin/AdminStatsCtrl.js

**Issues:**
- https://github.com/openmpf/openmpf/issues/1449
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1450)

Simon data is refreshed when clicking the Processes tab

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties

**Issues:**
- https://github.com/openmpf/openmpf/issues/1451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1452)

Make concurrent callbacks configurable.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MpfPropertiesConfigurationBuilder.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties

Merges: https://github.com/openmpf/openmpf/pull/1452
**Issues:**
- https://github.com/openmpf/openmpf/issues/1451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1453)

hf-merge/make-callback-connections-configurable

---

pom.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1458)

Update log4j to 2.16.0

---

pom.xml

Merges: https://github.com/openmpf/openmpf/pull/1458
**Issues:**
- https://github.com/openmpf/openmpf/issues/1457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1459)

hf-merge/update-log4j

---

pom.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1467)

Upgrade to log4j 2.17.1

---

pom.xml

Merges: https://github.com/openmpf/openmpf/pull/1467
**Issues:**
- https://github.com/openmpf/openmpf/issues/1466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1468)

hf-merge/log4j-2.17.1

---

trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsImage.json
trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsVideo.json

**Issues:**
- https://github.com/openmpf/openmpf/issues/1398
- https://github.com/openmpf/openmpf-components/pull/284
- https://github.com/openmpf/openmpf-docker/pull/161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1474)

Update expected JSON output files for system tests.

---

pom.xml
trunk/detection/executor/java/pom.xml
trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java
trunk/markup/pom.xml
trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java

- https://github.com/openmpf/openmpf/pull/1447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1484)

Remove dependency on org.apache.commons.io.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/MovingTrackLabelProcessor.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1487)

Fix bug where MOVING was being added to immutable map twice.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/MovingTrackLabelProcessor.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1488)

Hf merge/immutable map moving

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js

- https://github.com/openmpf/openmpf/pull/1447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1489)

Fix markup preview.

---

trunk/bin/mpf-scripts/mpf/mpf_nodes.py

- https://github.com/openmpf/openmpf/pull/1447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1493)

Fix "mpf list-nodes" command.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/mediainspection/TestMediaMetadataValidator.java

Merges: https://github.com/openmpf/openmpf/pull/1499
**Issues:**
- https://github.com/openmpf/openmpf/issues/1498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1506)

Hf merge/frame time info

---

pom.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1515)

Update Spring to 5.3.18

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1521)

Change S3 retry policy to retry for most errors

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java

Merges: https://github.com/openmpf/openmpf/pull/1521
**Issues:**
- https://github.com/openmpf/openmpf/issues/1520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1522)

hf-merge/s3-retry

---

trunk/detection/executor/cpp/streaming/CMakeLists.txt
trunk/detection/test-components/cpp/CplusplusHelloWorld/CMakeLists.txt
trunk/video-overlay/CMakeLists.txt

**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1518
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/112
- https://github.com/openmpf/openmpf-docker/pull/165
- https://github.com/openmpf/openmpf-components/pull/293
- https://github.com/openmpf/openmpf-contrib-components/pull/78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1518)

Update to OpenCV 4.5.5

---

trunk/detection/executor/cpp/streaming/CMakeLists.txt
trunk/detection/test-components/cpp/CplusplusHelloWorld/CMakeLists.txt
trunk/video-overlay/CMakeLists.txt

Merges: https://github.com/openmpf/openmpf/pull/1518
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1523
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/113
- https://github.com/openmpf/openmpf-docker/pull/166
- https://github.com/openmpf/openmpf-components/pull/294
- https://github.com/openmpf/openmpf-contrib-components/pull/79
- https://github.com/openmpf/openmpf.github.io/pull/150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1523)

Hf merge/ocv 4.5.5

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestS3StorageBackend.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1530
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1531)

Cache S3 client instances and properly close when done.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java
trunk/workflow-manager/src/main/resources/properties/mpf.properties
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestS3StorageBackend.java

Merges: https://github.com/openmpf/openmpf/pull/1531
**Issues:**
- https://github.com/openmpf/openmpf/issues/1530
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1532)

hf-merge/fix-s3-leak

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/MovingTrackLabelProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionSplitterImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/transformation/DetectionTransformationProcessor.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/DetectionErrorUtil.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/Media.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/AggregateJobPropertiesUtil.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/UserSpecifiedRangesUtil.java
trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/detection/TestMovingTrackLabelProcessor.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/TestArtifactExtractionSplitter.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionTaskSplitter.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/data/TestDetectionErrorUtil.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestS3StorageBackend.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestUserSpecifiedRangesUtil.java

Merges: https://github.com/openmpf/openmpf/pull/1584
**Issues:**
- https://github.com/openmpf/openmpf/issues/1583
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1590)

Hf merge/media optional fields

---

trunk/detection/executor/cpp/batch/main.cpp

Merges: https://github.com/openmpf/openmpf/pull/1587
**Issues:**
- https://github.com/openmpf/openmpf/issues/1586
- https://github.com/openmpf/openmpf/issues/1585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1591)

Hf merge/amq component bugs

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1580
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1593)

Fix NullPointerException in S3StorageBackend

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java

Merges: https://github.com/openmpf/openmpf/pull/1593
**Issues:**
- https://github.com/openmpf/openmpf/issues/1580
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1594)

Hf merge/s3 retry null pointer

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/Application.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/QueuePurgeService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/WfmStartup.java
trunk/workflow-manager/src/main/resources/applicationContext-camel.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1612
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1615)

Purge queues before CamelContext is created.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/QueuePurgeService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/WfmStartup.java
trunk/workflow-manager/src/main/resources/applicationContext-camel.xml

Merges: https://github.com/openmpf/openmpf/pull/1615
**Issues:**
- https://github.com/openmpf/openmpf/issues/1612
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1617)

Hf merge/queue purge

---

pom.xml
trunk/workflow-manager/pom.xml

Merges: https://github.com/openmpf/openmpf/pull/1636
**Issues:**
- https://github.com/openmpf/openmpf/issues/1635
- https://github.com/openmpf/openmpf-components/pull/316
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1638)

Update versions for trivvy issues (#1636)

---

trunk/workflow-manager/src/main/resources/properties/mpf-private-example.properties

**Issues:**
- https://github.com/openmpf/openmpf/issues/1658
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1655)

Use startup.auto.registration.skip.spring=false.

---

trunk/mpf-system-tests/src/test/resources/output/speech/runSpeechSphinxDetectVideo.json
trunk/mpf-system-tests/src/test/resources/output/text/runTextOalprDetectVideo.json
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java

Merges: https://github.com/openmpf/openmpf/pull/1664
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1665)

Hf merge/fix duration in tests

---

trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json
trunk/mpf-system-tests/src/test/resources/output/motion/runMogMotionPreprocessing.json
trunk/mpf-system-tests/src/test/resources/output/motion/runMogMotionPreprocessingFaceDetectionMarkup.json
trunk/mpf-system-tests/src/test/resources/output/motion/runMotionTracking.json

**Issues:**
- https://github.com/openmpf/openmpf/issues/1564
- https://github.com/openmpf/openmpf/issues/1342
- https://github.com/openmpf/openmpf/pull/1660
Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1672)

Update nightly test output

---

trunk/interop/src/main/java/org/mitre/mpf/interop/JsonMediaOutputObject.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/Media.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1650
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1673)

Add support for linked media

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/WorkflowPropertyService.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/AggregateJobPropertiesUtil.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/MediaActionProps.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestWorkflowPropertyService.java

Merges: https://github.com/openmpf/openmpf/pull/1708
**Issues:**
- https://github.com/openmpf/openmpf/issues/1707
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1709)

Hf merge/tiesdb uri mime type

---

pom.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1715
- https://github.com/openmpf/openmpf-docker/pull/198
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1716)

Use newer version of ActiveMQ library

---

trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json

Fixes test failure from https://github.com/openmpf/openmpf/pull/1644
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1724)

Fix nightly test

---

trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/OutputChecker.java
trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java

Merges: https://github.com/openmpf/openmpf/pull/1726
**Issues:**
- https://github.com/openmpf/openmpf/issues/1727
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1728)

Hf merge/ffmpeg version issue

---

pom.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1748
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1750)

Fix "NoSuchMethodError: 'void javax.jms.Message.setJMSDeliveryTime(long)'".

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/FfprobeMetadataExtractor.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1762
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1763)

Check if codec type is null.

---

trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/QueueInfo.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/QueueController.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1776
- https://github.com/openmpf/openmpf.github.io/pull/179
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1777)

Add queue end point

---

trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/QueueInfo.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/QueueController.java

Merges: https://github.com/openmpf/openmpf/pull/1777
**Issues:**
- https://github.com/openmpf/openmpf/issues/1776
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1778)

Hf merge/queue len

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1781
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1782)

Fix bug where markup boxes are not drawn when animation is disabled and there are gaps in a track.

---

trunk/workflow-manager/src/main/resources/workflow-properties.json

**Issues:**
- https://github.com/openmpf/openmpf/issues/1780
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1784)

Changed EXEMPLAR_POLICY to have a default value of QUALITY.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestVideoMediaSegmenter.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1805
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1806)

Always use pts to determine constant or variable frame rate.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestVideoMediaSegmenter.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java

Merges: https://github.com/openmpf/openmpf/pull/1806
**Issues:**
- https://github.com/openmpf/openmpf/issues/1805
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1807)

Hf merge/always use pts

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1819
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1820)

Fix splitterThreadPoolProfile

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java

Merges: https://github.com/openmpf/openmpf/pull/1820
**Issues:**
- https://github.com/openmpf/openmpf/issues/1819
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1824)

Hf merge/splitter threads

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Track.java

**Issues:**
-https://github.com/openmpf/openmpf/issues/1828
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1829)

fixed the parameter passed to getExemplar in the Track constructor.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Track.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1828
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1830)

Fixed parameter passed to getExemplar in the Track constructor

---

trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/OutputChecker.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/util/TestCloseableMdc.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1867
- https://github.com/openmpf/openmpf-docker/pull/225
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1868)

Test update props comparison and failing unit test

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/BatchJobStatusType.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java
trunk/workflow-manager/src/main/webapp/resources/js/services.js
trunk/workflow-manager/src/main/webapp/resources/layouts/jobs.html
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java

**Issues:**
-https://github.com/openmpf/openmpf/issues/1879
If a related issue doesn't exist, then create one first and assign it to yourself.
Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1886)

Merge COMPLETE_WITH_ERRORS into ERROR

---

trunk/video-overlay/src/main/cpp/HeifConverter.cpp
trunk/video-overlay/src/main/java/org/mitre/mpf/heif/HeifConverter.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/mediainspection/TestMediaMetadataValidator.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1903
- https://github.com/openmpf/openmpf-docker/pull/240
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1904)

Add AVIF support.

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessor.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1929)

changed artifact extraction to catch all exceptions

---

trunk/video-overlay/CMakeLists.txt
trunk/video-overlay/src/main/cpp/HeifConverter.cpp
trunk/video-overlay/src/main/java/org/mitre/mpf/frameextractor/FrameExtractor.java
trunk/video-overlay/src/main/java/org/mitre/mpf/heif/HeifConverter.java
trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/JniHeifLoader.java
trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/JniOcvLoader.java
trunk/workflow-manager/pom.xml

**Issues:**
- https://github.com/openmpf/openmpf/issues/1930
- https://github.com/openmpf/openmpf-docker/pull/247
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1941)

Created separate JNI libraries for heif and opencv functions

---

trunk/video-overlay/src/main/cpp/HeifConverter.cpp

**Issues:**
- https://github.com/openmpf/openmpf/issues/1943
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1944)

add wrapper class to free heif_image properly

---

trunk/video-overlay/src/main/cpp/HeifConverter.cpp

**Issues:**
- https://github.com/openmpf/openmpf/issues/1943
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1945)

hotfix merge for memory leak fix in HeifConverter

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java
trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestVideoMediaSegmenter.java
trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1940
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1948)

Added stopwatch timer to FrameTimeInfoBuilder

---

trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/AuthEventListener.java

**Issues:**
- https://github.com/openmpf/openmpf/issues/1960
Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf/1964)

Update login message.
